server:
  port: 8193

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8192"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8190
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8191
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8194
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
jwt:
  secret: jl23j02034jf0j3fiojsoijps09ug0j58jgoijoigj05u4g09i0a9ug=09aro2q0

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE